source 'https://rubygems.org'

gem 'pry'
gem 'sinatra', '>= 2.0.2'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'rubocop'
gem 'rspec'
gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'